### ISSUE TITLE
utility meter gas sensor

### ISSUE THREAD

**Issue by amgstone** [syssi/esphome-smg-ii#19]
I'm sorry that this is off topic, I'm trying to configure the gas meter, can you tell me if I configured the utility meter correctly?

**Comment by syssi** [comment]
Could you provide some details about your gas meter? How many pulses does the device send per m³?

**Comment by amgstone** [comment]
![Uploading IMG-37beab1198708fed02ee9e98945a899d-V.jpg…]()

**Comment by amgstone** [comment]
![IMG-37beab1198708fed02ee9e98945a899d-V](https://user-images.githubusercontent.com/63303107/222078374-4b4a9e4c-f7c6-464e-af09-24bd0e987cea.jpg)

**Comment by syssi** [comment]
https://www.samgas.com.ua/lichylnyk-gazu-membrannyy-samgaz-g25-rs2001-2
https://www.samgas.com.ua/sites/default/files/_samgaz_re_red_0_6_3_10-12-2018_14.pdf

I've trouble to translate the PDF document. Could you read the document and tell me the page which is about the low frequency pulses?

**Comment by syssi** [comment]
> On the last reel after the comma is fixed permanent magnet for working with a low-frequency pulse generator. The 
> design of the counting device has a plastic case in which the counting mechanism itself is assembled with the display
> display drums (Fig. 10):

**Comment by amgstone** [comment]
![IMG_20230301_115533_208](https://user-images.githubusercontent.com/63303107/222105484-e57647bc-46d3-4dab-a033-542db00970e4.jpg)
![IMG_20230301_115533_339](https://user-images.githubusercontent.com/63303107/222105512-b8f698c8-9015-4c3d-842f-f760a2d5a6f7.jpg)

**Comment by amgstone** [comment]
I install yaml, everything is ok, but as soon as I insert the reader into the gas meter, esp becomes offline.
![16776790712965149045181613314363](https://user-images.githubusercontent.com/63303107/222161518-ddb3f650-110e-4361-b3f2-1838c1a59a94.jpg)

**Comment by amgstone** [comment]
when the sensor is inserted into the gas meter, esp does not want to install yaml

**Comment by amgstone** [comment]
http://joxi.ru/l2ZYZB5Iz9wGlm

**Comment by amgstone** [comment]
after unplugging and turning on the power, esp starts counting from the beginning, does not remember the last value

**Comment by syssi** [comment]
I will have to build the setup on my own this evening to get an idea what's going on here.

**Comment by syssi** [comment]
```
globals:
  - id: total_pulses
    type: int
    restore_value: true
    initial_value: '7470502'

esphome:
  name: gas
  friendly_name: gaz

esp8266:
  board: esp01_1m
  restore_from_flash: true

preferences:
  flash_write_interval: 10min

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_wifi_ssid
    password: !secret ap_wifi_password

captive_portal:

binary_sensor:
  - platform: gpio
    id: reed
    pin:
      number: GPIO5
    name: "Reed contact closed"
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;
        - output.turn_off: led
    on_release:
      then:
        - output.turn_on: led

sensor:
  - platform: template
    name: "Gas Cubic meters used"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses) * 0.001;

output:
  - platform: gpio
    pin: GPIO2
    id: 'led'
```

Please attach the red wire to `GPIO5 / D1` and try again. :-)

**Comment by syssi** [comment]
I've tested the setup. It's working and the total pulses are stored every 10 minutes to the flash/rtc:

```
preferences:
  flash_write_interval: 10min
```

Does the LED of the wemos blink once on every round of the gas meter?

**Comment by amgstone** [comment]
with d1 does not respond

**Comment by syssi** [comment]
Could you try to describe the issue in detail? You could write the summary in your mother language if you like.

**Comment by amgstone** [comment]
when it was connected to d4, everything worked, but when I connected the sensor to the esp meter, it did not start. When I connected it to d1, the sensor did not work, did not react to the magnet.

**Comment by syssi** [comment]
You have to use a pull-up.

**Comment by amgstone** [comment]
and how should it be connected according to the scheme? I have resistors.

**Comment by syssi** [comment]
I will paint the schematics later the day!

**Comment by syssi** [comment]
I've enabled the internet pull-up of the ESP. Please try this updated YAML:

```
globals:
  - id: total_pulses
    type: int
    restore_value: true
    initial_value: '7470502'

esphome:
  name: gas
  friendly_name: gaz

esp8266:
  board: d1_mini
  restore_from_flash: true

preferences:
  flash_write_interval: 10min

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_wifi_ssid
    password: !secret ap_wifi_password

captive_portal:

binary_sensor:
  - platform: gpio
    id: reed
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
    name: "Reed contact closed"
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;
        - output.turn_off: led
    on_release:
      then:
        - output.turn_on: led

sensor:
  - platform: template
    name: "Gas Cubic meters used"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses) * 0.001;

output:
  - platform: gpio
    pin: GPIO2
    id: 'led'
```
