### ISSUE TITLE
Add additional controls of writable registers

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-smg-ii#43]
```
  # Output voltage                                        0.1V    Uint  320 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} output voltage"
    address: 320
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Output frequency setting                              0.01Hz  Uint  321 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} output frequency setting"
    address: 321
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "Hz"
    device_class: frequency
    # state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Battery overvoltage protection point                  0.1V    Uint  323 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} battery overvoltage protection point"
    address: 323
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Max charging voltage                                  0.1V    Uint  324 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} max charging voltage"
    address: 324
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Floating charging voltage                             0.1V    Uint  325 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} floating charging voltage"
    address: 325
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Battery discharge recovery point in mains mode        0.1V    Uint  326 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} battery discharge recovery point in mains mode"
    address: 326
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Battery low voltage protection point in mains mode    0.1V    Uint  327 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} battery low voltage protection point in mains mode"
    address: 327
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Battery low voltage protection point in off-grid mode 0.1V    Uint  329 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} battery low voltage protection point in off-grid mode"
    address: 329
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Maximum charging current                              0.1A    Uint  332 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} maximum charging current"
    address: 332
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "A"
    device_class: current
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Maximum mains charging current                        0.1A    Uint  333 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} maximum mains charging current"
    address: 333
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "A"
    device_class: current
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Eq Charging voltage                                   0.1V    Uint  334 1 R/W
  - platform: modbus_controller
    modbus_controller_id: smg0
    name: "${name} Eq Charging voltage"
    address: 334
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    # state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
```
